# Files
executable = scriptcondor_skimming.sh

# where to save log info (change to your directory)
output = /uscms/home/ekauffma/CMSSW_14_0_0_pre2/src/axo/axo_skimming/OUTPUTDIR/log/scriptcondor_$(ProcID).out
error = /uscms/home/ekauffma/CMSSW_14_0_0_pre2/src/axo/axo_skimming/OUTPUTDIR/log/scriptcondor_$(ProcID).err
log = /uscms/home/ekauffma/CMSSW_14_0_0_pre2/src/axo/axo_skimming/OUTPUTDIR/log/scriptcondor_$(ProcID).log

arguments            = FILENAMES /eos/uscms/store/user/lpctrig/ekauffma/Scouting_2024F_Skims/output_$(ClusterId)_$(ProcID).root

# File transfer behavior
#should_transfer_files = no
#when_to_transfer_output = ON_EXIT

# Resource requests
#request_cpus   = 4
#request_memory = 100MB
#request_disk   = 100MB
+JobFlavour = longlunch
getenv = True

requirements = (OpSysAndVer =?= "AlmaLinux9")

# Optional resource requests
#+xcount = 4            # Request 4 cores
#+maxMemory = 4000      # Request 4GB of RAM
#+maxWallTime = 120     # Request 2 hrs of wall clock time
#+remote_queue = "osg"  # Request the OSG queue

# Run job
queue
