# Files
executable = scriptcondor_skimming.sh

# where to save log info (change to your directory)
output = /afs/cern.ch/user/e/ekauffma/CMSSW_14_0_0_pre2/src/axo/axo_skimming/OUTPUTDIR/log/scriptcondor_$(Count).out
error = /afs/cern.ch/user/e/ekauffma/CMSSW_14_0_0_pre2/src/axo/axo_skimming/OUTPUTDIR/log/scriptcondor_$(Count).err
log = /afs/cern.ch/user/e/ekauffma/CMSSW_14_0_0_pre2/src/axo/axo_skimming/OUTPUTDIR/log/scriptcondor_$(Count).log

arguments            = FILENAMES OUTPUTFILENAME


transfer_input_files    = /afs/cern.ch/user/j/jpearkes/work/private/CMSSW_14_0_15/src/axo_skimming/x509_proxy, /afs/cern.ch/user/j/jpearkes/work/private/CMSSW_14_0_15/src/axo_skimming/skim.cxx, /afs/cern.ch/user/j/jpearkes/work/private/CMSSW_14_0_15/src/axo_skimming/axol1tl-producer, /afs/cern.ch/user/j/jpearkes/work/private/CMSSW_14_0_15/src/axo_skimming/run3_ugt_ml
# File transfer behavior
should_transfer_files = yes
#when_to_transfer_output = ON_EXIT

# Resource requests
#request_cpus   = 4
request_memory = 7000MB
request_disk   = 10000MB
+JobFlavour = "longlunch"
getenv = True

requirements = (OpSysAndVer =?= "AlmaLinux9")

# Optional resource requests
#+xcount = 4            # Request 4 cores
#+maxMemory = 7000      # Request 4GB of RAM
#+maxWallTime = 120     # Request 2 hrs of wall clock time
#+remote_queue = "osg"  # Request the OSG queue

# Run job
queue
